<a href="https://colab.research.google.com/github/eirenwibi/2025_KB_TI-1B/blob/main/Jobsheet2_KB.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#02. Operasi Matematika menggunakan Python

##a. Mendapatkan nilai minimum dan maksimum

In [4]:
x = min(5, 10, 25)
y = max(6, 12, 18)
print(x, y)

5 18


##b. Mendapat nilai absolut

In [5]:
x = abs(-7.25)
print(x)

7.25


##c. Mendapat nilai pangkat

In [6]:
import math
x = math.pow(4, 3)
print(x)

64.0


##d. Mendapatkan nilai akar

In [7]:
import math
x = math.sqrt(64)
print(x)

8.0


##e. Mendapatkan nilai pembulatan

In [8]:
import math
x = math.ceil(1.4)
y = math.floor(1.4)
print(x, y)

2 1


##f. Mendapatkan nilai konstanta (PI)

In [9]:
import math
x = math.pi
print(x)

3.141592653589793


#03. Menggunakan Fungsi MATH

In [15]:
import math

def main():
    x = float(input("Masukkan nilai x: "))
    y = float(input("Masukkan nilai y (untuk operasi yang memerlukan dua angka): "))
    n = int(input("Masukkan nilai n (bilangan bulat untuk faktorial dan permutasi): "))
    k = int(input("Masukkan nilai k (bilangan bulat untuk permutasi): "))

    print("\nHasil Perhitungan:")
    print(f"sin({x}) = {math.sin(x)}")
    print(f"cos({x}) = {math.cos(x)}")
    print(f"tan({x}) = {math.tan(x)}")
    print(f"log({x}) = {math.log(x)}")
    print(f"log10({x}) = {math.log10(x)}")
    print(f"degrees({x}) = {math.degrees(x)}")
    print(f"dist([{x}], [{y}]) = {math.dist([x], [y])}")
    print(f"factorial({n}) = {math.factorial(n)}")
    print(f"fmod({x}, {y}) = {math.fmod(x, y)}")
    print(f"isnan({x}) = {math.isnan(x)}")
    print(f"gamma({x}) = {math.gamma(x)}")
    print(f"perm({n}, {k}) = {math.perm(n, k)}")

if __name__ == "__main__":
    main()

Masukkan nilai x: 10
Masukkan nilai y (untuk operasi yang memerlukan dua angka): 20
Masukkan nilai n (bilangan bulat untuk faktorial dan permutasi): 30
Masukkan nilai k (bilangan bulat untuk permutasi): 40

Hasil Perhitungan:
sin(10.0) = -0.5440211108893698
cos(10.0) = -0.8390715290764524
tan(10.0) = 0.6483608274590866
log(10.0) = 2.302585092994046
log10(10.0) = 1.0
degrees(10.0) = 572.9577951308232
dist([10.0], [20.0]) = 10.0
factorial(30) = 265252859812191058636308480000000
fmod(10.0, 20.0) = 10.0
isnan(10.0) = False
gamma(10.0) = 362880.0
perm(30, 40) = 0


#04. Operasi Matriks dan Vektor dengan Python

##a. Membuat matriks di Python

In [16]:
import numpy as np
A = np.array([[80, 30, 25],
              [50, 20, 10]])
B = np.array([[30, 60, 15],
              [10, 30, 30]])
hasil = A + B
print(hasil)

[[110  90  40]
 [ 60  50  40]]


##b. Melakukan operasi dot product

In [18]:
import numpy as np
A = np.array([10, 20, 15])
B = np.array([16, 67, 35])
hasil = np.dot(A, B)
print(hasil)

2025


##c. Melakukan operasi cross product

In [19]:
import numpy as np
A = np.array([10, 20, 15])
B = np.array([16, 67, 35])
hasil = np.cross(A, B)
print(hasil)

[-305 -110  350]


#TUGAS PRAKTIKUM

##01. Tentukan hasil perkalian berikut menggunakan kode python :

In [21]:
import numpy as np
A = np.array([[3, 1],
             [2, 0]])
B = np.array([[2,1],
             [1, -1]])
hasil = np.dot(A, B)
print(hasil)

[[7 2]
 [4 2]]


In [24]:
import numpy as np
B = np.array([[2, 1],
              [1, -1]]),
C = np.array([[-1, 1, 2],
              [2, 0, -1]])
hasil = np.dot(B, C)
print(hasil)

[[[ 0  2  3]
  [-3  1  3]]]


##02. Hitunglah nilai dari soal faktorial berikut :

In [25]:
import math

faktorial_6 = math.factorial(6)
faktorial_8_5 = math.factorial(8) // math.factorial(5)

print(f"Nilai 6! adalah : {faktorial_6}")
print(f"Nilai 8! / 5! adalah : {faktorial_8_5}")

Nilai 6! adalah : 720
Nilai 8! / 5! adalah : 336


##03. Tentukan panjang masing - masing Vektor, hasil perkalian titik A.B, dan AxB

In [26]:
import numpy as np

A = np.array([5, 3, 7])
B = np.array([12, -3, 1])

panjang_A = np.linalg.norm(A)
panjang_B = np.linalg.norm(B)

dot_product = np.dot(A, B)

cross_product = np.cross(A, B)

print(f"Panjang vektor A: {panjang_A:.2f}")
print(f"Panjang vektor B: {panjang_B:.2f}")
print(f"A . B = {dot_product}")
print(f"A x B = {cross_product}")

Panjang vektor A: 9.11
Panjang vektor B: 12.41
A . B = 58
A x B = [ 24  79 -51]
